version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: homellc-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 6equj5_root
      MYSQL_DATABASE: home_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 6equj5_db_user
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
